PrincetonUniversity/SPECFEMPP

CMakeLists.txt
DATA/source.yaml
docs/index.rst
docs/parameter_documentation/databases.rst
docs/source_description/index.rst
include/source.h
include/source_time_function.h
include/utils.h
src/read_sources.cpp
src/source.cpp
src/source_time_function.cpp
src/specfem2d.cpp
tests/unittests/displacement_tests/Newmark/serial/sources.yaml
tests/unittests/domain/serial/data/source.yaml
tests/unittests/source/serial/sources.yml

In this pull request we added support for command line parsing of parameter file argument. 
Changed the organization of source files. The YAML is more intuitative and robust with force and moment_tensor sources implemented as nodes and STFs implemented as a child node. 
[x] I ran the code through pre-commit to check style
[x] I have added sufficient unittests to test my changes
[x] I have added/updated documentation for the changes I am proposing
[x] I have updated CMakeLists to ensure my code builds
[x] My code builds across all platforms

Added support for command line parsing

---

DATA/specfem_config.yaml
docs/parameter_documentation/index.rst
docs/user_documentation/running_the_solver.rst
include/material.h
include/mesh.h
include/parameter_parser.h
include/source.h
include/specfem_mpi.h
src/boundaries.cpp
src/material.cpp
src/mesh.cpp
src/mpi_interfaces.cpp
src/parameter_parser.cpp
src/read_material_properties.cpp
src/solver.cpp
src/source.cpp
src/specfem2d.cpp
src/timescheme.cpp
tests/unittests/displacement_tests/Newmark/newmark_tests.cpp

Updated user output to console
[x] I ran the code through pre-commit to check style
[x] I have added sufficient unittests to test my changes
[x] I have added/updated documentation for the changes I am proposing
[x] I have updated CMakeLists to ensure my code builds
[x] My code builds across all platforms

Update user output

---

docs/parameter_documentation/databases.rst
docs/user_documentation/mesh_generation.rst

Define mesh database parameters.
[x] I ran the code through pre-commit to check style
[x] I have added sufficient unittests to test my changes
[x] I have added/updated documentation for the changes I am proposing
[x] I have updated CMakeLists to ensure my code builds
[x] My code builds across all platforms

Updated mesh documentation

---

include/material/acoustic_material.hpp
include/material/elastic_material.hpp
src/material/acoustic_material.cpp
src/material/elastic_material.cpp
src/mesh/IO/fortran/read_material_properties.cpp

Updates the ```acoustic_material``` class with a working constructor and associated print and ```get_properties``` function. 
#68 

Update acoustic material class

---

CMakeLists.txt
docs/user_documentation/installation.rst
include/compute/compute_properties.hpp
src/compute/compute_properties.cpp
tests/unit-tests/compute/elastic/compute_properties_tests.cpp

Add a parameter `h_kappa` for acoustic material properties.
Issue number [#67](https://github.com/PrincetonUniversity/specfem2d_kokkos/issues/67)

Read acoustic material properties

---

include/domain/acoustic/acoustic_domain.tpp
include/domain/impl/sources/acoustic/acoustic2d.hpp
include/domain/impl/sources/acoustic/acoustic2d_isotropic.hpp
include/domain/impl/sources/acoustic/acoustic2d_isotropic.tpp
include/domain/impl/sources/interface.hpp
src/parameter_parser/setup.cpp
tests/unit-tests/displacement_tests/Newmark/elastic/serial/specfem_config.yaml
tests/unit-tests/domain/elastic/serial/specfem_config.yaml
tests/unit-tests/seismogram/serial/specfem_config.yaml

[x] I ran the code through pre-commit to check style
[x] My code passes all the integration tests
[x] I have added sufficient unittests to test my changes
[x] I have added/updated documentation for the changes I am proposing
[x] I have updated CMakeLists to ensure my code builds
[x] My code builds across all platforms

Set default seismogram output as ascii.

---

.github/workflows/compilation.yml
.github/workflows/unittests.yml
.jenkins/unittests.gvy

Added `-DBUILD_TESTS=ON` to `.github/workflows/unittests.yml` and `.jenkins/unittests.gvy`
Issue [#63](https://github.com/PrincetonUniversity/specfem2d_kokkos/pull/75)

Add -DBUILD_TESTS=ON to the cmake commands accordingly

---

include/compute/compute_properties.hpp
include/domain/acoustic/acoustic_domain.hpp
include/domain/acoustic/acoustic_domain.tpp
include/domain/impl/elements/acoustic/acoustic2d.hpp
include/solver/time_marching.tpp
src/compute/compute_properties.cpp

Compiling but not running.

---

.devcontainer/devcontainer.json
.github/workflows/docker.yml
.gitignore
Dockerfile
docs/examples/fluid-solid-interface/interfaces_fluid_flat.dat
docs/examples/homogeneous-medium-flat-topography/topography.dat
examples/fluid-solid-interface/Par_File.in
examples/fluid-solid-interface/topography.dat
examples/homogeneous-medium-flat-topography/topography.dat
meshfem2d/force_ftz.c

This PR 
- creates a dockerbuild for devel, latest (main) and ref tags. 
- Adds a devcontainer to be used as SPECFEM++ playground for demo purposes

Dockerfile

---

tests/unit-tests/assembly/test_config.yaml

Implements issue #123 
closes #123 

Compute kernels test

---

CMakeLists.txt
docs/api/setup_parameters/display.rst
docs/api/setup_parameters/index.rst
docs/api/setup_parameters/wavefield_writer.rst
include/enumerations/display.hpp
include/parameter_parser/setup.hpp
include/parameter_parser/writer/plot_wavefield.hpp
include/parameter_parser/writer/wavefield.hpp
include/writer/plot_wavefield.hpp
src/parameter_parser/setup.cpp
src/parameter_parser/writer/plot_wavefield.cpp

Added display section to runtime configuration

---

include/enumerations/display.hpp
src/parameter_parser/writer/plot_wavefield.cpp
src/plotter/plot_wavefield.cpp

Implements adding colors to elements based on material types

---

.github/pull_request_template.md
docs/getting_started/index.rst
include/IO/ASCII/impl/datasetbase.hpp
include/parameter_parser/setup.hpp
meshfem2d/CMakeLists.txt
src/parameter_parser/setup.cpp
src/specfem2d.cpp

Adresses tracking issue and subtasks.
- #155
+ #152 
+ #153  
- Updated the issue template to include the spaces required for the checklist because I got frustrated.
- Added line to compiler support table in the getting started section of the documentation.

Fix for Apple clang compilation

---

CMakeLists.txt
docs/api/IO/Libraries/mesh/index.rst
docs/api/IO/Libraries/sources/index.rst
docs/api/IO/index.rst
include/IO/mesh/read_mesh.hpp
include/IO/receivers/read_receivers.hpp
include/receiver/interface.hpp
src/IO/receivers/read_receivers.cpp
tests/unit-tests/seismogram/acoustic/seismogram_tests.cpp
tests/unit-tests/seismogram/elastic/seismogram_tests.cpp

Moves receiver read to the IO module
adresses #169

Move receivers read to IO namespace

---

docs/parameter_documentation/simulation_setup.rst

Added display section to docs

---

.jenkins/gnu_compiler_checks.gvy
.jenkins/intel_compiler_checks.gvy
.jenkins/nvidia_compiler_checks.gvy

Updated Jenkins artifact folder

---

.jenkins/gnu_compiler_checks.gvy
.jenkins/intel_compiler_checks.gvy
.jenkins/nvidia_compiler_checks.gvy
CMakeLists.txt

Adds separate workdirs for every matrix build 

Jenkins fix for GNU tests

---

pyproject.toml

Remove unused build-system
#234

Remove [build-system]

---

include/point/sources.hpp

Implementation of point source type

---

docs/index.rst
include/material/elastic_properties.hpp
include/mesh/materials/materials.hpp
src/IO/mesh/impl/fortran/read_material_properties.cpp
src/mesh/materials/materials.cpp
src/plotter/plot_wavefield.cpp

Implemented new anisotropic material::properties and the allowed for reading

---

CMakeLists.txt

Fixed Apple clang cmake issues

---

include/compute/kernels/impl/kernels_container.hpp
include/compute/kernels/kernels.hpp
include/compute/properties/impl/properties_container.hpp
tests/unit-tests/assembly/kernels/kernels.cpp

Implement kernels_container
Closes #274 and #275

Implement kernels_container

---

examples/Tromp_2005/plot.py
include/compute/kernels/impl/kernels_container.hpp
include/writer/kernel.tpp
src/compute/compute_kernels.cpp
tests/unit-tests/assembly/kernels/kernels.cpp

Implements kernel writer. Based on  #304 
Closes #299

kernel writer

---

include/domain/impl/kernels.hpp
include/domain/impl/kernels.tpp
include/writer/kernel.tpp
src/compute/assembly/compute_wavefield.cpp
src/compute/compute_kernels.cpp

Fixed seg fault on displacement tests & Fixed wavefield computation 

Fixed seg faults on tests | Fixed wavefield plotting

---

include/compute/kernels/kernels.hpp
include/writer/kernel.tpp
src/compute/compute_kernels.cpp

Implement kernel ispec getter and apply to kernel writer.
Closes #310 

Get element indices of a kernel medium

---

CMakeLists.txt
docs/source_description/source_discription.rst
docs/source_description/source_time_function_description.rst
examples/CMakeLists.txt
examples/solid-solid-interface/CMakeFiles/Par_File.in
examples/solid-solid-interface/CMakeFiles/specfem_config.yaml.in
examples/solid-solid-interface/CMakeLists.txt
examples/solid-solid-interface/README.md
examples/solid-solid-interface/Snakefile
examples/solid-solid-interface/sources.yaml
examples/solid-solid-interface/topography.dat
include/source_time_function/gaussiander.hpp
include/source_time_function/interface.hpp
src/plotter/plot_wavefield.cpp
src/source/source.cpp
src/source/utilities.cpp
src/source_time_function/gaussiander.cpp
src/source_time_function/utilities.cpp

adds example directory solid-solid-interface from the computational seismology class in at princeton.
Requires #382 to be merged first.
- Also increases resolution of the VTK output images to 2560x2560 pixels.
Closes #369 

Issue 369 - Adds homework 9 from JT's class

---

src/quadrature/gll/gll_utils.cpp

Remove sprintf

---

include/kokkos_kernels/impl/compute_source_interaction.tpp
include/kokkos_kernels/impl/compute_stiffness_interaction.tpp

Fix stacey boundary for backward simulation

---

tests/unit-tests/assembly/sources/sources.cpp
tests/unit-tests/utilities/include/compare_array.tpp

final fixes for intel compiler

Gpu compilation fix

---

.jenkins/gnu_compiler_checks.gvy
.jenkins/intel_compiler_checks.gvy
.jenkins/nvidia_compiler_checks.gvy

Issue 451 - Updated the OpenMP tests

---

.gitignore
examples/dim3/homogeneous_halfspace/specfem_config.yaml
fortran/meshfem3d/generate_databases/CMakeLists.txt
fortran/meshfem3d/generate_databases/create_regions_mesh.f90
fortran/meshfem3d/generate_databases/save_arrays_solver.F90
fortran/meshfem3d/generate_databases/save_parameters.f90
fortran/meshfem3d/generate_databases/setup_mesh.f90

Implemented a parameter writer like `specfem3d_globe` to create `mesh_parameters.bin`
Closes #457 

Issue 457 -- Implement Meshfem Parameter writer

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Updated the template

---

docs/conf.py
docs/requirements.txt

Fix for readthedocs build failing

---

include/compute/fields/data_access.tpp

Fix a typo in impl_store_on_device.
Closes #514 

Fix typo in impl_store_on_device.

---

CMakeLists.txt
docs/parameter_documentation/simulation_setup.rst
include/IO/property/reader.tpp
include/IO/property/writer.tpp
include/compute/impl/value_containers.hpp
include/parameter_parser/elastic_wave.hpp
include/parameter_parser/setup.hpp
src/compute/compute_kernels.cpp
src/compute/compute_properties.cpp
src/compute/compute_receivers.cpp
src/compute/compute_sources.cpp
src/execute.cpp
src/parameter_parser/elastic_wave.cpp
src/parameter_parser/setup.cpp
tests/unit-tests/assembly/kernels/kernels.cpp
tests/unit-tests/assembly/properties/properties.cpp

- Macro usage (compute kernels and sources)
- Adds macros to generate member variables 
- Generate return value in member variables with macro
- Adds elastic wave to parameter parser
closes #512, closes #526

Updates compute kernels and properties to use macros, updates writers, updates parameter parser

---

docs/requirements.txt
pyproject.toml
uv.lock

Updated 
- `uv.lock`
- `docs/requirements.txt`
- `pyproj.toml`
What the title says
Closes #580 

Issue 580 - sphinx_design version  number fix

---

.github/workflows/compilation.yml
.github/workflows/unittests.yml
.gitmodules
.jenkins/gnu_compiler_checks.gvy
.jenkins/intel_compiler_checks.gvy
.jenkins/nvidia_compiler_checks.gvy
.jenkins/unittests.gvy
Dockerfile
docs/getting_started/index.rst
docs/getting_started/installation.rst

Ran
```
git rm boost
```
Closes #573 

Issue 573 - Removes boost submodule

---

src/IO/mesh/impl/fortran/dim2/read_mesh_database.cpp

Updated the mesher reading

---

.github/ISSUE_TEMPLATE/project_task.md

Add issue template for project tasks 

---

include/medium/dim2/poroelastic/isotropic/material.hpp
include/point/impl/point_data.hpp
tests/unit-tests/CMakeLists.txt
tests/unit-tests/mesh/materials/materials.cpp
tests/unit-tests/mesh/materials/properties.cpp
tests/unit-tests/mesh/test_config.yaml

Implements checks for derived properties computed from base properties defined in the database. 

Added test to check get_properties function

---

include/kokkos_kernels/impl/compute_stiffness_interaction.tpp
include/medium/damping_force.hpp

Implements damping term
closes #623 

Added damping forces

---

tests/unit-tests/displacement_tests/Newmark/test_config.yaml

Fixed minor bug in test config yaml

---

src/compute/assembly/compute_wavefield.cpp
src/periodic_tasks/plot_wavefield.cpp

- added new colors to `periodic_tasks/plot_wavefield.cpp`
- added comments to `generate_wavefield`
#658

Issue 658 -- Implement colors for plotting of EM and Poroelastic domains.

---

include/medium/dim2/poroelastic/isotropic/kernels_container.hpp
include/medium/kernels_container.hpp
include/point/kernels.hpp

Implemented kernels for poroelastic
closes issue #599 

Issue 599 - implemented kernels for poroelastic

---

CMakeLists.txt
include/medium/dim2/poroelastic/isotropic/properties_container.hpp
include/medium/properties_container.hpp
tests/unit-tests/CMakeLists.txt

Issue-602 Implemented properties_container 

---

include/IO/wavefield/reader.tpp
include/IO/wavefield/writer.tpp
include/compute/boundary_values/boundary_values_container.hpp
include/compute/boundary_values/boundary_values_container.tpp
include/compute/fields/simulation_field.hpp
include/compute/fields/simulation_field.tpp

Wavefield files and stacey boundary container for poroelastic
closes issue #598 

Issue 598 - wavefield files and stacey boundary container for poroelastic

---

examples/CMakeLists.txt
examples/electromagnetic_no_damping_GPR_TE/.gitignore
examples/electromagnetic_no_damping_GPR_TE/CMakeFiles/Par_File.in
examples/electromagnetic_no_damping_GPR_TE/CMakeFiles/Snakefile.in
examples/electromagnetic_no_damping_GPR_TE/CMakeFiles/specfem_config.yaml.in
examples/electromagnetic_no_damping_GPR_TE/CMakeLists.txt
examples/electromagnetic_no_damping_GPR_TE/README.md
examples/electromagnetic_no_damping_GPR_TE/topography.dat

Meshing works, but changed the example to
- Remove absorbing boundaries (requires Stacey implementation)
- No damping term (Requires damping implementation)
CLoses #675 

Issue 675 - EM implements a basic example from Morency 2020 with implementation constraints

---

include/compute/properties/properties.hpp
include/medium/properties_container.hpp
src/compute/assembly/assembly.cpp
src/compute/compute_properties.cpp

Fixes bug related to property assignment at GLL points

---

.github/workflows/compilation.yml
.github/workflows/unittests.yml

Updated
- `.github/workflows/compilation.yml`
- `.github/workflows/unit_tests.yml`
no issue number

Update the github workflow to test upon pull request

---

tests/unit-tests/assembly/properties/properties.cpp

Updated properties tests with correct PE properties

Updated properties tests with correct PE properties

---

include/point/kernels.hpp
tests/unit-tests/assembly/kernels/kernels.cpp
tests/unit-tests/assembly/properties/properties.cpp

Modified the tes files kernels and properties for poroelastic
closes issue 603-test

issue 603-test - Modified the tes files kernels and properties for poroelastic

---

tests/unit-tests/displacement_tests/Newmark/test_config.yaml

Ran displacement test!!
closes issue #611 

issue 611 - Ran displacement test!!

---

include/medium/damping_force.hpp
include/medium/dim2/poroelastic/isotropic/damping.hpp

Added viscous damping file for poroelastic
closes issue #700 

issue 700 - Added viscous damping file for poroelastic

---

fortran/meshfem2d/read_material_table.f90
fortran/meshfem2d/save_databases.f90
fortran/meshfem2d/setup/constants.h.in
fortran/meshfem2d/shared_par.f90

We are trying to add spin to the kokkos version of specfem2d based on Jeroen's notes, following the fairly successful implementation of poroelasticity.
@danielpeter , I think I got everything that I need for the meshing the new material. Could you double check? Am I missing something obvious?
Thank you!

Add spin material fortran mesher

---

CMakeLists.txt
include/enumerations/material_definitions.hpp
include/enumerations/medium.hpp
include/point/kernels.hpp
include/point/properties.hpp
src/enumerations/medium.cpp

- Added elastic_psv_t
- Updates point/properties
- Updates point/kernels
Closes #723 
Closes #724 
Closes #725 

Issue 723 724 725 - Enumerations, point_properties, point_kernels

---

.github/workflows/compilation.yml
.github/workflows/unittests.yml
.jenkins/gnu_compiler_checks.gvy
.jenkins/intel_compiler_checks.gvy

Updated compilation and test workflows

---

.jenkins/gnu_compiler_checks.gvy
.jenkins/intel_compiler_checks.gvy
.jenkins/nvidia_compiler_checks.gvy

Updated compilers available on della9

---

tests/unit-tests/assembly/sources/sources.cpp

- Adds function `check_load()` to test
- Fix index error in loading `check_load()`
Closes #778 

Issue 778 - fix function check_load in assembly source test

---

docs/parameter_documentation/index.rst
include/compute/assembly/assembly.hpp
src/compute/assembly/assembly.cpp
src/execute.cpp

Issue 784 - Updated the parameter doc & added print function for assembly

---

include/compute/compute_partial_derivatives.hpp
include/kokkos_kernels/impl/compute_mass_matrix.tpp
include/kokkos_kernels/impl/compute_material_derivatives.tpp
include/kokkos_kernels/impl/compute_seismogram.tpp
include/kokkos_kernels/impl/compute_source_interaction.tpp
include/kokkos_kernels/impl/divide_mass_matrix.tpp
include/kokkos_kernels/impl/invert_mass_matrix.tpp
include/medium/dim2/elastic/isotropic/wavefield.hpp
include/medium/impl/accessor.hpp
include/medium/impl/data_container.hpp

Final set of optimizations

---

include/enumerations/medium.hpp

Adds attributes for a 3D elastic field
Adds to #809 

Added elastic dim3 element attributes

---

CMakeLists.txt
tests/unit-tests/CMakeLists.txt

* Latest commit fixes include issue mentioned [here](https://github.com/jbeder/yaml-cpp/pull/1310)
* Fixes issues related to cmake minimum policy version. Mentioned [here](https://github.com/jbeder/yaml-cpp/commit/c9371de7836d113c0b14bfa15ca70f00ebb3ac6f)
* Fixes issues releated to cmake minimum policy version. Mentioned [here](https://github.com/google/googletest/pull/4744)
@lsawade can you make sure this fixes #781
Closes #840 
Closes #781 

Updates YAML and GoogleTest version

---

include/medium/dim2/poroelastic/isotropic/damping.hpp

Added missing factor to damping computation

---

core/specfem/point/partial_derivatives.hpp
include/compute/compute_partial_derivatives.hpp
include/enumerations/accessor.hpp
include/enumerations/container.hpp
include/enumerations/data_class.hpp
include/enumerations/interface.hpp

Add Accessor for `point_partial_derivatives` and Container for partial derivative container.
Partially implements #832 

Issue 809 accessor

---

core/specfem/point/properties.hpp
docs/sections/getting_started/index.rst

Just made a small update to getting started documenation clarifying that required dependencies are automatically installed and removed a doc string that was throwing a warning that will be added/modified in another PR anyways
Closes #694 

Issue 694 - Updated the Documentaion and removed Lambda G additional member docstring

---

include/algorithms/divergence.hpp
include/algorithms/gradient.hpp
include/chunk_element/index.hpp
include/compute/fields/data_access.tpp
include/compute/fields/simulation_field.hpp
include/domain_view.hpp
include/execution/chunked_domain_iterator.hpp
include/kokkos_kernels/impl/compute_mass_matrix.tpp
include/kokkos_kernels/impl/compute_stiffness_interaction.tpp
include/medium/impl/accessor.hpp

Adds chunked domain iterator

---

src/parameter_parser/elastic_wave.cpp

Relaxes the input of elastic-wave parameter.
Closes #883 

Fix elastic-wave parameter input.

---

docs/index.rst
docs/sections/getting_started/index.rst

Updated the capabilities and the compiler table

---

CMakeLists.txt
core/specfem/point/partial_derivatives.hpp
include/boundary_conditions/dirichlet/dirichlet.hpp
include/compute/fields/data_access.tpp
include/datatypes/simd.hpp
include/execution/for_each_level.hpp
include/kokkos_abstractions.h
include/kokkos_kernels/impl/divide_mass_matrix.tpp
include/kokkos_kernels/impl/invert_mass_matrix.tpp
include/medium/dim2/elastic/isotropic/wavefield.hpp
include/timescheme/newmark.tpp
tests/unit-tests/CMakeLists.txt
tests/unit-tests/assembly/properties/properties.cpp
tests/unit-tests/datatypes/simd_tests.cpp
tests/unit-tests/point/kernels/dim2/acoustic_isotropic.cpp
tests/unit-tests/point/kernels/dim2/elastic_anisotropic.cpp
tests/unit-tests/point/kernels/dim2/elastic_isotropic.cpp
tests/unit-tests/point/kernels/dim3/elastic_isotropic.cpp
tests/unit-tests/point/properties/dim2/acoustic_isotropic.cpp
tests/unit-tests/point/properties/dim2/elastic_anisotropic.cpp
tests/unit-tests/point/properties/dim2/elastic_isotropic.cpp
tests/unit-tests/point/properties/dim2/electromagnetic_isotropic.cpp
tests/unit-tests/point/properties/dim2/poroelastic_isotropic.cpp

Update Kokkos version to 4.6.1

---

docs/sections/api/index.rst
docs/sections/api/macros/config_strings.rst
docs/sections/api/macros/data_container.rst
docs/sections/api/macros/for_each_in_product.rst
docs/sections/api/macros/index.rst
docs/sections/api/macros/point_container.rst

Adds documentation on
- POINT_CONTAINER
- FOR_EACH_IN_PRODUCT
- DATA_CONTAINER
- CONFIG_STRINGS
Closes #929 

Add documentation on macros.

---

core/specfem/point/stress.hpp
tests/unit-tests/CMakeLists.txt
tests/unit-tests/stress/dim2/acoustic.cpp
tests/unit-tests/stress/dim2/elastic_anisotropic.cpp
tests/unit-tests/stress/dim2/elastic_isotropic.cpp
tests/unit-tests/stress/dim2/elastic_isotropic_cosserat.cpp
tests/unit-tests/stress/dim2/poroelastic_isotropic.cpp

Added unit tests for stress computation

---

CMakeLists.txt
fortran/meshfem3d/generate_databases/save_arrays_solver.F90
fortran/meshfem3d/generate_databases/save_parameters.f90
include/io/mesh/impl/fortran/dim3/interface.hpp
include/io/mesh/impl/fortran/dim3/interface.tpp
include/io/mesh/impl/fortran/dim3/utilities.hpp
include/mesh/dim3/control_nodes/control_nodes.hpp
include/mesh/dim3/mapping/mapping.hpp
include/mesh/dim3/mesh.hpp
include/mesh/dim3/parameters/parameters.hpp
src/io/mesh/impl/fortran/dim3/mesh.cpp
src/io/mesh/impl/fortran/dim3/read_parameters.cpp
src/mesh/dim3/control_nodes/control_nodes.cpp
src/mesh/dim3/mesh.cpp
src/specfem3d.cpp

Updated fortran mesher to write control nodes

---

.github/workflows/compilation.yml
.github/workflows/unittests.yml
core/specfem/assembly/fields/dim2/simulation_field.cpp
core/specfem/assembly/fields/dim2/simulation_field.tpp
core/specfem/assembly/fields/dim3/simulation_field.cpp
core/specfem/assembly/fields/dim3/simulation_field.tpp

Fixed simulation field compilation

---

include/medium/compute_stress.hpp
include/medium/dim3/elastic/isotropic/stress.hpp
tests/unit-tests/CMakeLists.txt
tests/unit-tests/stress/dim3/elastic_isotropic.cpp

Adds 3d stress computation 
Closes #1120

Issue 1120 - Added 3d elastic isotropic stress and associated unit-tests
