PrincetonUniversity/SPECFEMPP

CMakeLists.txt
docs/user_documentation/requirements.rst

Added CMake feature to look for local boost.
If `boost>=1.73.0` is installed and `$BOOST_ROOT` is `cmake` will look for as well as the necessary components. If the necessary components cannot be found, `cmake` will install 
On Della:
```bash
module load boost/1.73.0
cmake3 -S . -B build_cpu
cmake3 --build build_cpu -j
```
Partially fixes #63 

Adding local boost support to CMake configuration.

---

include/domain/acoustic/acoustic_domain.tpp
include/domain/elastic/elastic_domain.tpp
src/compute/compute.cpp
src/compute/compute_partial_derivatives.cpp

Changes calculation of ix, iz to utilise the sub2ind function instead
65 
[ x ] I ran the code through pre-commit to check style
[] n/a: My code passes all the integration tests
[ x ] I have added sufficient unittests to test my changes
[] n/a: I have added/updated documentation for the changes I am proposing
[] n/a: I have updated CMakeLists to ensure my code builds
[] n/a: My code builds across all platforms

Change to sub2ind function

---

CMakeLists.txt
docs/user_documentation/installation.rst

Added BUILD_TESTS flag to `CMakeLists.txt`. The default is set to OFF. To enable BUILD_TESTS flag, added `-DBUILD_TESTS=ON` to the command during the compilation.
Issue [#63](https://github.com/PrincetonUniversity/specfem2d_kokkos/issues/63)

Compile tests only when required - Only compile tests when BUILD_TESTS flags is ON

---

include/compute/compute_mesh.hpp
include/mesh/control_nodes/control_nodes.hpp
include/mesh/mesh.hpp
src/IO/mesh.cpp
src/compute/compute_mesh.cpp

Implemented specfem::mesh::control_nodes with template specialization.

---

CMakeLists.txt
include/IO/mesh/impl/fortran/read_parameters.hpp
include/mesh/mesh.hpp
include/mesh/parameters/parameters.hpp
src/IO/mesh.cpp
src/IO/mesh/impl/fortran/read_parameters.cpp

Implements #202 
- renamed `specfem::mesh::properties` to `specfem::mesh::parameters`
Closes #202 

Implemented templates for specfem::mesh::parameters

---

include/IO/mesh/impl/fortran/read_boundaries.hpp
include/compute/boundaries/impl/acoustic_free_surface.hpp
include/compute/boundaries/impl/stacey.hpp
include/mesh/boundaries/absorbing_boundaries.hpp
include/mesh/boundaries/acoustic_free_surface.hpp
include/mesh/boundaries/boundaries.hpp
include/mesh/boundaries/forcing_boundaries.hpp
include/mesh/mesh.hpp
include/mesh/tags/tags.hpp
src/IO/mesh/impl/fortran/read_boundaries.cpp
src/compute/boundaries/impl/acoustic_free_surface.cpp
src/compute/boundaries/impl/stacey.cpp
src/mesh/boundaries/absorbing_boundaries.cpp
src/mesh/boundaries/acoustic_free_surface.cpp
src/mesh/boundaries/forcing_boundaries.cpp
src/mesh/tags/tags.cpp

Implemented templates of mesh::boundary

---

include/IO/mesh/impl/fortran/read_elements.hpp
include/mesh/elements/axial_elements.hpp
include/mesh/elements/tangential_elements.hpp
include/mesh/mesh.hpp
src/IO/mesh/impl/fortran/read_elements.cpp
src/mesh/elements/axial_elements.cpp
src/mesh/elements/tangential_elements.cpp

Adds dimension flag to all
closes #207, closes #208 

Implements dimension specific axial and tangential elements

---

include/IO/interface.hpp
include/compute/assembly/assembly.hpp
include/compute/boundaries/boundaries.hpp
include/compute/coupled_interfaces/coupled_interfaces.hpp
include/compute/coupled_interfaces/interface_container.hpp
include/compute/coupled_interfaces/interface_container.tpp
include/mesh/mesh.hpp
src/IO/mesh.cpp
src/compute/assembly/assembly.cpp
src/compute/boundaries/boundaries.cpp
src/compute/coupled_interfaces.cpp
src/mesh/mesh.cpp
src/specfem2d.cpp

After all elements of the mesh were fixed to be templated as a function of dimension, the `mesh` struct was the last thing remaining. This address that "shortcoming".
Closes #221 

Implements a dimension templated mesh struct.

---

include/specfem_mpi/specfem_mpi.hpp
src/specfem2d.cpp
src/specfem_mpi/specfem_mpi.cpp

Update for MPI_PARALLEL flag

---

include/compute/impl/value_containers.hpp
include/compute/properties/impl/properties_container.hpp
include/material/acoustic_properties.hpp
include/point/properties.hpp

Rename lambdaplus2mu to kappa for acoustic.
Closes #340 

Rename lambdaplus2mu to kappa for acoustic

---

CMakeLists.txt
tests/unit-tests/CMakeLists.txt

The hash for the boost download changed, which is a dependency that is outside of this repo that could change anytime again. This pull request introduces a fast way to build  boost from the official repo's release zips, only building the required libraries.
It should fix previous build issues.
Closes #357 

Issue 357 - Fix Boost installation to remove non-official dependency

---

.github/workflows/docker.yml
Dockerfile

Manually installs cmake, since the Debian repo is not installing version>=3.19.
closes #355

Issue 355 -- Fixing docker image creation

---

fortran/meshfem3d/meshfem3D/CMakeLists.txt
fortran/meshfem3d/shared/CMakeLists.txt
fortran/meshfem3d/shared/command_line_arguments.f90
fortran/meshfem3d/shared/read_parameter_file.F90
fortran/meshfem3d/shared/read_value_parameters.f90
fortran/meshfem3d/shared/shared_par.F90

Implements command line parser for the 3D mesher

---

fortran/meshfem3d/generate_databases/save_arrays_solver.F90

Updates IO for save array solver
Closes #391 

Updated the save_database function to write element by element

---

.jenkins/gnu_compiler_checks.gvy
.jenkins/intel_compiler_checks.gvy
.jenkins/nvidia_compiler_checks.gvy
CMakeLists.txt

- Updates the kokkos module to 4.5.01 
- Updates boost minimum required module to 1.85.0 
Closes #428 

Updated boost and kokkos modules

---

examples/dim3/homogeneous_halfspace/DATA/meshfem3D_files/Mesh_Par_file
examples/dim3/homogeneous_halfspace/DATA/meshfem3D_files/interfaces.txt
examples/dim3/homogeneous_halfspace/Par_File
fortran/meshfem3d/CMakeLists.txt
fortran/meshfem3d/generate_databases/fault_generate_databases.f90
fortran/meshfem3d/generate_databases/generate_databases.f90
fortran/meshfem3d/generate_databases/model_coupled.f90
fortran/meshfem3d/meshfem3D/create_interfaces_mesh.f90
fortran/meshfem3d/meshfem3D/determine_cavity.f90
fortran/meshfem3d/meshfem3D/meshfem3D.F90
fortran/meshfem3d/meshfem3D/read_mesh_parameter_file.f90
fortran/meshfem3d/setup/constants.h
fortran/meshfem3d/setup/constants.h.in
fortran/meshfem3d/shared/count_number_of_sources.f90
fortran/meshfem3d/shared/read_parameter_file.F90
fortran/meshfem3d/shared/read_value_parameters.f90
fortran/meshfem3d/shared/shared_par.F90

Removes the directory structure restrictions for `xmeshfem3D` and `xgenerate_databases` executibles. The file and directory paths are now added within the Par_file
Closes #423 

Make the directory structure for 3D mesher flexible

---

CMakeLists.txt
CMakePresets.json
examples/dim3/homogeneous_halfspace/specfem_config.yaml
fortran/meshfem3d/generate_databases/save_parameters.f90
include/IO/interface.hpp
include/IO/mesh/impl/fortran/dim3/read_parameters.hpp
include/mesh/mesh.hpp
include/mesh/parameters/parameters.hpp
include/parameter_parser/database_configuration.hpp
include/parameter_parser/setup.hpp
src/IO/mesh.cpp
src/IO/mesh/impl/fortran/dim3/read_parameters.cpp
src/parameter_parser/database_configuration.cpp
src/specfem3d.cpp

Implements the reader for the `mesh_parameters.bin` file
I also implemented a first CMake preset that we can add on to (#450). I will probably add the remaining presets in the next PR. As a result you now can
You can now configure a serial debug version using
```bash
cmake --preset debug && cmake --build --preset debug
```
This will build in the `build/debug` directory, so to access `specfem2d`, you have to
```bash
export PATH="path/to/SPECFEMPP/build/debug/bin/":$PATH
```
**IMPORTANT**: This of course breaks the tests since the tests are built with relative directory locations. We need to add working directories for the tests in `./tests/CMakeLists.txt`.
Closes #461, partially addresses #450 .

Issue 461 -- Implement Parameter Reader 

---

CMakeLists.txt
CMakePresets.json

I was not able to reproduce the NVIDIA compilation error or Della8.
Added more presets along the way
- release-cuda
- debug-cuda
```bash
cmake --preset release-cuda
cmake --build --preset cuda [-j]
```
Aimed at della compilation for A100s. 
Closes #482

Issue 482 - Fix cuda compilation + new presets

---

include/algorithms/divergence.hpp
include/algorithms/gradient.hpp
include/compute/fields/data_access.tpp
include/compute/fields/impl/field_impl.tpp
include/kokkos_kernels/impl/compute_stiffness_interaction.tpp
include/parallel_configuration/chunk_config.hpp
src/compute/compute_mesh.cpp

This PR updates global index mapping i.e. `specfem::compute::points::index_mapping` to account for `chunk_size` used within the compute kernels. This serializes accesses to assembled fields resulting in better performance. 
**I will add performance curve here once the simulations finish running**
closes #481 

Global index mapping reordering 

---

include/enumerations/material_definitions.hpp
include/enumerations/medium.hpp
include/kokkos_kernels/domain_kernels.hpp
src/enumerations/medium.cpp

Adds elastic_sh tag to medium_tag enumerations
- Updates medium.hpp and material_definitions.hpp to include elastic_sh enumeration
- Updates medium_tag specific methods within enumerations
closes #495 

Add elastic shear wave enumerations

---

include/IO/impl/medium_writer.hpp
include/IO/impl/medium_writer.tpp
include/IO/kernel/writer.tpp
include/IO/property/writer.tpp
src/IO/kernel/writer.cpp
src/IO/property/writer.cpp

Merge kernel and property writer.
Closes #550

Merge kernel and property writer

---

CMakeLists.txt
include/periodic_tasks/check_signal.hpp
pyproject.toml
src/periodic_tasks/check_signal.cpp
src/python/core.cpp

This PR fixes the ability to interrupt the execution of the execute function from python and continue to work in the terminal. The issue at the end was that I was throwing an error in the signal_handler that is passed to the `signal(int signal, static void func(int i)` handling function from the `signal.h` C header. This caused the program to segfault. The solution is the following.
In our `periodic_tasks/check_signal.hpp` create an atomic flag:
```cpp
// Global flag for signal state - must be volatile sig_atomic_t for thread safety
volatile sig_atomic_t signal_received = 0;
```
and updated this flag through the handler:
```cpp
// Static function to handle signals
static void signal_handler(int code) {
// Just set the flag and return
signal_received = code;
std::cout << "Signal " << code …
```

Issue 574 - Fixing the execution from Python + VTK_CXX_BUILD=OFF works now even if VTK is found

---

include/enumerations/macros_impl/element_types.hpp
include/enumerations/macros_impl/material_systems.hpp
include/enumerations/macros_impl/medium_tags.hpp
include/enumerations/macros_impl/utils.hpp
include/enumerations/material_definitions.hpp

This PR is just a re-organization and doesn't introduce anything new.
- Move all private macros to a new folder named macros_impl
- Add underscore to all private macros
- Move macros out of namespace specfem::medium to avoid confusion
- Make temporary macros like MAKE_ARRAY_ELEM to permanent like MAKE_ARRAY_ELEM_MAT_SYS
- Add more comments to explain the usage of macros
Closes #752 

Issue 752 - Re-organize current macros

---

.jenkins/gnu_compiler_checks.gvy
.jenkins/intel_compiler_checks.gvy

Skylake nodes were removed from the SLURM queue in the last system downtime. Update intel CI slurm constraint to `intel|cascade`.

Fixed Intel CI after system update

---

CMakeLists.txt
examples/Tromp_2005/Snakefile
include/io/wavefield/reader.hpp
include/io/wavefield/reader.tpp
include/io/wavefield/writer.hpp
include/io/wavefield/writer.tpp
include/io/writer.hpp
include/parameter_parser/setup.hpp
include/parameter_parser/writer/wavefield.hpp
include/periodic_tasks/check_signal.hpp
include/periodic_tasks/periodic_task.hpp
include/periodic_tasks/plot_wavefield.hpp
include/periodic_tasks/wavefield_reader.hpp
include/periodic_tasks/wavefield_writer.hpp
include/solver/time_marching.tpp
include/utilities/string.hpp
include/utilities/strings.hpp
src/execute.cpp
src/parameter_parser/writer/wavefield.cpp
src/periodic_tasks/check_signal.cpp
src/periodic_tasks/plot_wavefield.cpp
src/periodic_tasks/wavefield_reader.cpp
src/periodic_tasks/wavefield_writer.cpp
src/utilities/string.cpp
src/utilities/strings.cpp
tests/unit-tests/CMakeLists.txt

- Remove property `m_istep` from periodic_tasks
- Add `assembly` and `istep` to `periodic_task->run` parameters
- Add wavefield write configuration `time_interval`
- Add options `include_last_step` to periodic_tasks
- Add `utilities/string.hpp` for string utilities
- Change wavefield reader / writer to periodic_task
Closes #783 

Issue 783 - Add option to write wavefield every N timesteps

---

fortran/meshfem2d/read_parameter_file.F90
src/io/mesh/impl/fortran/dim2/read_parameters.cpp

Updates to mesher parameters to run CUBIT

---

CMakeLists.txt
examples/Tromp_2005/Snakefile
include/io/ASCII/impl/file.hpp
include/io/HDF5/impl/file.hpp
include/io/reader.hpp
include/io/wavefield/reader.hpp
include/io/wavefield/reader.tpp
include/io/wavefield/writer.hpp
include/io/wavefield/writer.tpp
include/io/writer.hpp
include/periodic_tasks/periodic_task.hpp
include/periodic_tasks/wavefield_reader.hpp
include/periodic_tasks/wavefield_writer.hpp
include/solver/time_marching.tpp
include/utilities/strings.hpp
pyproject.toml
src/parameter_parser/writer/wavefield.cpp
src/periodic_tasks/wavefield_reader.cpp
src/periodic_tasks/wavefield_writer.cpp
src/utilities/strings.cpp
uv.lock

- Add flush() method for writing changes to disk without closing the file
- Add h5py to examples group dependency for future analysis
- wavefield reader / writer is no longer subclass of io::reader / writer because the require an additional istep parameter as well as initializers
- Write coordinate information in wavefield writer
- Add initialize() / finalize() for periodic tasks
Closes #793 

Issue 793 - Write wavefield data of different time steps into a single file.

---

include/compute/assembly/assembly.hpp
include/compute/receivers/receivers.hpp
include/enumerations/specfem_enums.hpp
include/parameter_parser/receivers.hpp
include/parameter_parser/setup.hpp
src/compute/assembly/assembly.cpp
src/compute/compute_receivers.cpp
src/parameter_parser/receivers.cpp
tests/unit-tests/assembly/test_fixture/test_fixture.cpp
tests/unit-tests/domain/rmass_inverse_tests.cpp

- Removed seismogram type because the only place it was used was to convert it to wavefield type
Closes #773 

Removed the seismogram type and replaced it with wavefield type

---

include/algorithms/divergence.hpp
include/datatypes/chunk_element_view.hpp
include/kokkos_kernels/impl/compute_stiffness_interaction.tpp

Updated `ChunkVectorViewType` layouts. Similar to #693 this issue updates the order of indexing for vector view types. 
Closes #693 

Updated chunk vector view layouts

---

include/enumerations/macros_impl/array.hpp
include/enumerations/macros_impl/expand_seq.hpp
include/enumerations/macros_impl/utils.hpp
include/enumerations/material_definitions.hpp

Rewrite `_EXPAND_SEQ` in a similar way as `BOOST_PP_SEQ_FOR_EACH` to reduce the amout of preprocessing.
Closes #805 

Issue 805 - Optimize compilation for macros

---

include/kokkos_kernels/impl/compute_mass_matrix.tpp
include/kokkos_kernels/impl/compute_material_derivatives.tpp
include/kokkos_kernels/impl/compute_stiffness_interaction.tpp
include/parallel_configuration/chunk_config.hpp

Setting `SIMD = false` greatly improves performance on device code 
Nsight systems report shows `compute_stiffness_interaction` routine speed up of ~30% (~900 microsec -> 600 microsec)
Closes #466 

Sets SIMD flag to false for device code

---

include/kokkos_kernels/impl/compute_mass_matrix.tpp
include/kokkos_kernels/impl/compute_material_derivatives.tpp
include/kokkos_kernels/impl/compute_seismogram.tpp
include/kokkos_kernels/impl/compute_source_interaction.tpp
include/kokkos_kernels/impl/compute_stiffness_interaction.tpp
include/kokkos_kernels/impl/divide_mass_matrix.tpp
include/kokkos_kernels/impl/invert_mass_matrix.tpp
include/parallel_configuration/range_config.hpp
include/policies/chunk.hpp
include/policies/range.hpp
include/timescheme/newmark.tpp
src/compute/assembly/helper.hpp
tests/unit-tests/policies/policies.cpp

Added tiling for Range loops

---

src/parameter_parser/database_configuration.cpp

Checks parameter keys directly instead of number of keys.
Closes #821

Issue 821 - Update if condition if mesh parameter parser

---

CMakeLists.txt
benchmarks/src/CMakeLists.txt
fortran/meshfem2d/setup/CMakeLists.txt
fortran/meshfem3d/setup/CMakeLists.txt

Added all remaining files to the clean target.
The user now can 
```bash
cmake --build <build_dir> --target clean
make clean
cmake --build --preset <presetname>--target clean
```
Closes #856 

Issue 856 - implemented a clean target

---

include/utilities/simd.hpp
tests/unit-tests/point/boundary_tests.cpp
tests/unit-tests/point/kernels/dim2/acoustic_isotropic.cpp
tests/unit-tests/point/kernels/dim2/elastic_anisotropic.cpp
tests/unit-tests/point/kernels/dim2/elastic_isotropic.cpp
tests/unit-tests/point/kernels/dim2/poroelastic_isotropic.cpp
tests/unit-tests/point/kernels/dim3/elastic_isotropic.cpp
tests/unit-tests/point/partial_derivatives_tests.cpp
tests/unit-tests/point/properties/dim2/acoustic_isotropic.cpp
tests/unit-tests/point/properties/dim2/elastic_anisotropic.cpp
tests/unit-tests/point/properties/dim2/elastic_isotropic.cpp
tests/unit-tests/point/properties/dim2/electromagnetic_isotropic.cpp
tests/unit-tests/point/properties/dim2/poroelastic_isotropic.cpp
tests/unit-tests/point/properties/dim3/elastic_isotropic.cpp
tests/unit-tests/point/stress_integrand_tests.cpp
tests/unit-tests/point/stress_tests.cpp

- Added function `specfem::utilities::is_close` that checks relative tolerance for both simd and non-simd values.
- Apply `is_close` to point tests.
Closes #905

Issue 905 - add is_close() utility and apply to point tests

---

include/io/ASCII/impl/datasetbase.hpp
include/io/ASCII/impl/native_type.tpp

@icui we can run Tromp-2005 in ASCII mode after this update

Fix ASCII Reader/Writer

---

core/specfem/assembly/mesh/dim2/impl/points.hpp
core/specfem/assembly/mesh/dim2/impl/utilities.hpp
core/specfem/assembly/mesh/dim2/impl/utilities.tpp
core/specfem/assembly/mesh/dim2/mesh.tpp
tests/unit-tests/CMakeLists.txt
tests/unit-tests/assembly/mesh/utilities.cpp

Implements testable functions for the assign numbering function, which makes the numbering scheme usable without an assembly. which in turn can be used for the locate point unit tests in the following PR.
Updates #1057 

Issue 1057 -- Splits mesh numbering intro testable functions, and implements tests

---

tests/unit-tests/jacobian/dim2/compute_jacobian_tests.cpp
tests/unit-tests/jacobian/dim2/compute_locations_tests.cpp
tests/unit-tests/jacobian/dim3/compute_jacobian_tests.cpp
tests/unit-tests/jacobian/dim3/compute_locations_tests.cpp

Update the jacobian tests to create the control node views within the fixture, so that, if new tests need to be added, the control node arrays do not need to be recomputed.
Closes #1130 

Issue 1130 - Updated the jacobian tests

---

core/specfem/source/dim2/vector_source/force_source.cpp
include/medium/dim2/acoustic/isotropic/source.hpp
include/source_time_function/ricker.hpp
src/source_time_function/dgaussian.cpp
src/source_time_function/dirac.cpp
src/source_time_function/ricker.cpp
tests/unit-tests/displacement_tests/Newmark/serial/HomogeneousElasticIsotropicDomainSH/sources.yaml
tests/unit-tests/source/dim2/vector_sources/force_source.hpp

The changes should reflect [SPECFEM2D's PR #1259](https://github.com/SPECFEM/specfem2d/pull/1259) that updates the implementation of the source time function to more accurately match SPECFEM3D.
The way the acoustic force source_array was applied in the medium/compute_source had the wrong sign as a result of legacy code. One result of this is the definition of the source angle was inverted.
- Removing of negative signs in the compute_source_time_function member functions of the Ricker, Delta, dGaussian functions, e.g. 
- Updating sign and cosines in the angle computation of the elastic force 
- change sign of the operation of the potential in `medium/compute_source<acoustic>` from 
acc(...) += source_array(...) to   acc(...) -= source_array(...) 
Closes #945
Please make sure to check …

Issue 945 - Updates the STF and force implementations to match SPECFEM2D Fortran

---

include/algorithms/locate_point.hpp
include/algorithms/locate_point_impl.hpp
src/algorithms/dim2/locate_point.cpp
src/algorithms/dim2/locate_point_impl.cpp
tests/unit-tests/CMakeLists.txt
tests/unit-tests/assembly/locate/locate_point_on_edge.cpp

Adds a function in `specfem::algorithms` to compute local coordinates on a known edge and element, using a similar argument configuration as the other `locate_point` functions.
This will be needed for computing the reparameterizations of nonconforming interfaces.
resolves #1155

Edge-based locate point

---

CMakeLists.txt
cmake/boost.cmake

A merge from devel-dg into devel caused remnants to be re-added to the CMakeLists.txt. This PR - removes these remnants
- fixes an issue that is introduced by using Boost==1.89 and cmake 4, where cmake won't find the Boost::system library since it is header only

Fixes cmake issues with boost etc.
